# fly.toml app configuration file generated for shwordle on 2023-09-22T21:00:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shwordle"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
